### ISSUE TITLE
meta-karo split BSP

### ISSUE THREAD

**Issue by luzik** [karo-electronics/meta-karo#1]
Please consider splitting meta-karo into essential BSP packages (like recipes-kernel, recipes-bsp/u-boot/, meta-karo/conf/machine/) and the rest of distro related packages.
Now I am unable to build my own distro without overwriting yours bbappends files in my layer.
For example you are forcing me to get your private bash aliases and break my read-only rootfs moving files from volatiles.
This is OK for your distro, but adding meta-karo layer shouldn't affect others layers packages, only those required to build essential BSP.
Please let me know when you read this, because last time there were same issue with notifications.

**Comment by oliverwendt** [comment]
1. It's not yet officially released, i.e.: subject to change.

2. This uses the Yocto framework to implement the small footprint RFS
   (incl. Linux & U-Boot) we otherwise always provid(ed) at our customer
   download area.
   
3. The read-only RFS implementation in normal Yocto is broken.

**Comment by luzik** [comment]
I'm also you customer and a yocto user too.
As your RootFS is really great for fresh users - it allows easy run and customize linux on your TX embedded world, in more advanced implementation it breaks Yocto layers idea, because your customers have to modify your layer - what is great for fresh dive into Linux customization - but doesn't give a flexibility for using with own layer schem.
My idea is to split your layer into two - bsp and the rest of it. With a relative small effort you would provide flexibility for customers with own layers and do not break anything for your own software production workflow, nor for fresh TX users.

**Comment by luzik** [comment]
For someone who want to include meta-karo on its own layer:

```
mkdir meta-karo
cd meta-karo
git init
git remote add -f origin https://github.com/karo-electronics/meta-karo.git
git config core.sparsecheckout true
echo recipes-bsp/ >> .git/info/sparse-checkout
echo recipes-kernel/ >> .git/info/sparse-checkout
echo conf/machine/ >> .git/info/sparse-checkout
echo classes/kernel-localversion.bbclass >> .git/info/sparse-checkout
echo conf/layer.conf >> .git/info/sparse-checkout
sed -i '/FILESYSTEM_PERMS_TABLES/d' conf/layer.conf
```

now you can add `meta-karo` to your own `conf/bblayers.conf`

note that default KARO u-boot do not compile under rocko default gcc, so use bin provided by karo

**Comment by lw-karo** [comment]
There are instructions how to build U-Boot in README.adoc:
|Building the U-Boot boot loader currently requires a different
|tool-chain and therefore a different basic configuration:
|
|MACHINE=tx6q-1030 source ./setup-environment build-tx6q-1030
|bitbake u-boot
...

**Comment by theonlymb** [comment]
BSP is splitted into *meta-karo* and *meta-karo-distro* in current release.
