### ISSUE TITLE
linux-karo.bb overwrite KERNEL_DEVICETREE from machine definition

### ISSUE THREAD

**Issue by luzik** [karo-electronics/meta-karo#4]
I am unable to set `KERNEL_DEVICETREE` from my custom machine definition, probably because of `KERNEL_DEVICETREE_imx*` in recipes-kernel/linux/linux-karo_%.bb

**Comment by luzik** [comment]
If this is a way it should work, please remove confusing definition from machine

**Comment by lw-karo** [comment]
This has been fixed in Release 2018-06-25
