### ISSUE TITLE
kernel 4.14 : GPU / VPU / IPU

### ISSUE THREAD

**Issue by bealr** [karo-electronics/meta-karo#6]
Hi,

When I try to run "Qt5_CinematicExperience --platform eglfs" the system try to open "/usr/lib/dri/etnaviv_dri.so" and this file not exists. In this folder i only have "swrast_dri.so".
How can I build the etnaviv driver?

Can I use VPU / GPU / IPU with the 4.14 kernel ?

If I can't use meta-freescale and i can't include imx-vpu. How can I use the vpu with gstreamer? With Krogoth / 4.1.15 I was using mxc-vpu in gstreamer line.
Same question for IPU: i was using imxv4l2videosrc with Krogoth. Does the Rocko /4.14 support the IPU directly with v4l2src ?

Romain

**Comment by lw-karo** [comment]
Did you try the 'karo-x11' DISTRO?
Please refer to:
https://github.com/karo-electronics/karo-bsp
